# Main constants
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
TITLE = "Pong"

# Paddle constants
PADDLE_LENGTH = 1
PADDLE_WIDTH = 5
PADDLE_POSX = 350
PADDLE_POSY = 0
PADDLE_SPEED = 20
RIGHT = "R"
LEFT = "L"

# Ball constants
BALL_POSX = 0
BALL_POSY = 0
BALL_SLEEP = 0.1
BALL_STEPS = 10
BALL_DIAMETER = 20
BALL_X_LIMIT = PADDLE_POSX - 30
BALL_Y_LIMIT = SCREEN_HEIGHT / 2 - BALL_DIAMETER
BALL_PADDLE_DIST = 50

# Score Board constants
ALIGNMENT = "center"
FONT = ("Courier", 40, "normal")
SCORE_Y = 250
SCORE_X = 100